---
- name: Install python2.7
  apt:
    name: python2.7
    state: present

- name: Get Stouts.python
  command: ansible-galaxy install Stouts.python
  register: stouts
  changed_when: "'is already installed' not in stouts.stderr"
  failed_when: "'ERROR' in stouts.stderr"
- name: Install python virtualenv
  apt:
    name: python-virtualenv
    state: present

- name: Install python3 virtualenv
  apt:
    name: python3-virtualenv
    state: present

#- name: Include Stouts.python
#  include_role:
#    name: Stouts.python

- name: Install Python 2 virtualenv packages
  pip: 
    name: 
    - pip
    virtualenv: "{{python_virtualenvs.0.path}}"
    state: latest

- name: Install Python 3 virtualenv packages
  pip: 
    name: 
    - pip
    virtualenv: "{{python_virtualenvs.1.path}}"
    state: latest
